config/routes.rb
Rails.application.routes.draw do
  # home index
  root to: 'application#home'

  get '/home',
      to: 'application#home',
      as: 'home'

  # auth
  get '/login',
      to: 'application#login',
      as: 'login'

  get '/signout', 
      to: 'application#signout', 
      as: 'signout'

  get '/logout',
      to: 'application#logout',
      as: 'logout'

  # buildings
  get '/buildings',
      to: 'buildings#list',
      as: 'building_list'

  get '/buildings/:id/employees',
      to: 'buildings#employees',
      as: 'building_employees'

  get '/buildings/:id',
      to: 'buildings#details',
      as: 'building_details'

  # employees
  get 'employees',
      to: 'employees#list',
      as: 'employee_list'

  get '/employee/:id',
      to: 'employees#profile',
      as: 'employee_profile'

  # departments
  get 'departments',
      to: 'department#list',
      as: 'department_list'

  get 'departments/:id',
      to: 'department#details',
      as: 'department_details'

  get 'departments/:id/employees',
      to: 'department#employees',
      as: 'department_employees'

  # liaisons
  get '/liaisons',
      to: 'liaison#list',
      as: 'liaisons_list'
  get '/subjects', to: redirect('/liaisons', status: 302)

  # search
  get '/search',
      to: 'search#index',
      as: 'search_index'

  # admin
  get '/admin',
      to: 'admin#home',
      as: 'admin_home'

  # phone lists
  get '/phonelist/morgantown', to: 'phone_list#morgantown'
  get '/phonelist/all', to: 'phone_list#all'

  # API
  namespace :api do
    namespace :v1, defaults: { format: :json } do
        # buildings
        get '/buildings/:id/employees', to: 'buildings#employees'
        get '/buildings/:id', to: 'buildings#details'
        get '/buildings', to: 'buildings#list'

        # departments
        get '/departments', to: 'departments#list'
        get '/departments/:id', to: 'departments#details'
        get '/departments/:id/employees', to: 'departments#employees'
        
        # employees
        get 'employees', to: 'employees#list'
        get 'employees/:id', to: 'employees#profile'
    end
  end

  # admin namespaces for crud tasks
  namespace :admin do
    resources :buildings,
              :departments,
              :employees,
              :floors,
              :subjects,
              :service_points

    resources :employees do
      resources :leadership, only: [:index, :edit, :update, :destroy]
    end
  end
end

app/models/department.rb
# Library Departments
#
# @author David J. Davis
# @data_model
# @since 0.0.1
class Department < ApplicationRecord
  # validation
  validates :name,
            presence: true,
            length: { within: 5..50 }

  validates :description,
            length: { maximum: 500 }

  # associations
  belongs_to :building
  has_many :service_points, -> { order(:name) }, dependent: :destroy
  has_many :phones, as: :phoneable, dependent: :destroy
  has_many :emails, as: :emailable, dependent: :destroy

  has_many :departmentable, dependent: :nullify
  has_many :employees, -> { order(:last_name, :first_name) }, through: :departmentable

  # active status
  enum status: %i[enabled disabled]

  # form logic
  accepts_nested_attributes_for :service_points, allow_destroy: true
  accepts_nested_attributes_for :phones, allow_destroy: true
  accepts_nested_attributes_for :emails, allow_destroy: true

  # search
  include Searchable

  # return building name for search index
  def building_name
    building.name.to_s
  end

  # scopes
  scope :visible, -> { where(status: 'enabled') }
  scope :order_name, -> { order(:name) }

  # Elastic Search Settings
  # -----------------------------------------------------

  # Elastic Search Index settings.
  # These are set in the model to index only specific information.   
  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :type
      indexes :name
      indexes :description
      indexes :status
    end
  end

  # Elasticsearch indexed json searches for boosting search relevancy. 
  # @author David J. Davis
  def as_indexed_json(_options)  
    as_json(
      methods: [:building_name],
      only: [:id, :status, :name, :building_name],
      include: {
        service_points: { only: :name },
        phones: { only: :number },
        emails: { only: :address }
      }
    )
  end
end

app/controllers/admin/departments_controller.rb
# Departments Controller
# @author David J. Davis, Tracy A. McCormick
# Sets data for views, sets redirects, sets errors
class Admin::DepartmentsController < AdminController
  # before_actions
  before_action :set_department, only: %i[show edit update destroy]

  # GET admin/departments
  # GET admin/departments.json
  def index
    @departments = Department.all.includes(:building).order(:name)
  end

  # GET /departments/1
  # GET /departments/1.json
  def show; end

  # GET /departments/new
  def new
    @department = Department.new
    @buildings =  Building.all.order(:name)
  end

  # GET /departments/1/edit
  def edit; end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)
    respond_to do |format|
      if @department.save
        format.html { redirect_to admin_department_path(@department), success: I18n.t('department.success') }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to admin_department_path(@department), success: I18n.t('department.edited') }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to '/admin/departments', success: I18n.t('department.deleted') }
    end
  end

  # Private Methods
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_department
    @department = Department.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def department_params
    params.require(:department)
          .permit(:building,
                  :building_id,
                  :name,
                  :description,
                  phones_attributes: %i[id number_types number _destroy],
                  emails_attributes: %i[id address _destroy])
  end
end

app/controllers/api/v1/departments_controller.rb
class Api::V1::DepartmentsController < ApplicationController
  # concerns
  include PublishApi
  before_action :public_headers


  # serializers
  include Version1::DepartmentsSerializer
  include Version1::EmployeesSerializer

  def list
    departments = Department.includes(:building, :phones)
                            .order(:name)
    render json: serialize_departments(departments)
  end

  def employees
    employees = Employee.includes(:departments, :departmentable, :addresses, :phones)
                        .where(
                          status: 'enabled',
                          departments: { id: params[:id] }
                        )
                        .order(:last_name, :first_name)
    render json: serialize_employees(employees)
  end

  def details
    department = Department.includes(:service_points,
                                     :phones,
                                     :building,
                                     service_points: [:phones]).find(params[:id])

    render json: serialize_department(department)
  end
end

app/controllers/department_controller.rb
class DepartmentController < ApplicationController
  def list
    @departments = Department.includes(:building, :phones)
                             .order(:name)
  end

  def employees
    @department = Department.find(params[:id])
    @employees = Employee.includes(:departments, :departmentable, :addresses, :phones)
                         .where(
                           status: 'enabled',
                           departments: { id: params[:id] }
                         )
                         .order(:last_name, :first_name)
  end

  def details
    @department = Department.includes(:service_points,
                                      :phones,
                                      :building,
                                      service_points: [:phones]).find(params[:id] )
  end
end

app/views/admin/departments/_form.html.erb
<%= form_for [:admin, department], html: { multipart: true } do |f| %>
  <% if department.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(department.errors.count, "Error") %> </h3> 
      <p> The following prohibited this department from being saved: </p>
      <ul>
      <% department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :building_id, "Building", class: 'required' %>
    <div class="select-style">
      <%= f.collection_select :building_id, Building.all, :id, :name, { prompt: 'Building for Department' } %>
    </div>
  </div>

  <div class="field">
    <%= f.label :name, class: 'required' %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <!-- Phones -->
  <%= f.fields_for :phones do |form| %>
    <%= render "phone", form: form %>
  <% end %>
  <%= link_to_add_fields "Add Phones", f, :phones %>

  <!-- Emails -->
  <%= f.fields_for :emails do |form| %>
    <%= render "email", form: form %>
  <% end %>
  <%= link_to_add_fields "Add Emails", f, :emails %>  

  <div class="actions">
    <%= link_to 'Cancel', admin_departments_path, class: 'cancel-button' %>
    <%= f.submit 'Submit', class: 'submit-button' %>
  </div>
<% end %>

app/views/admin/departments/edit.html.erb
<h2>Editing <%= @department.name %> </h2>

<%= render 'form', department: @department %>

app/views/admin/departments/index.html.erb
<div class="top-action">
  <h2> Manage Departments </h2>
  <%= link_to 'New Department', new_admin_department_path, { class: 'new-button' } %>
</div>

<% @departments.each do |dept| %>
  <div class="crud-list department-list">
    <div class="text-attributes">
      <ul>
        <li> 
          <strong> Name: </strong> 
          <%= dept.name %>
        </li>

        <li> 
          <strong> Description: </strong> 
          <%= dept.description %>
        </li>

        <li>
          <strong> Building: </strong>
          <%= dept.building.name %>
        </li>

        <% if dept.phones.present? %>
        <li>
          <strong> Department Phone Numbers: </strong>
          <ul class="phone">
            <% dept.phones.each do |phone| %>
            <li>
              <strong> <%= phone.number_types.capitalize %>:  </strong>
              <a href="tel:<%= phone.number %>">
                <%= phone.number %> 
              </a> 
            </li>
            <% end %>
          </ul>
        </li>
        <% end %>

        <% if dept.emails.present? %>
        <li>
          <strong> Department Email Addresses: </strong>
          <ul class="email">
            <% dept.emails.each do |email| %>
            <li>
              <a href="mailto:<%= email.address %>">
                <%= email.address %>
              </a>
            </li>
            <% end %>
          </ul>
        </li>
        <% end %>        

        <% if dept.service_points.present? %>
        <li> 
          <% dept.service_points.each do |sp| %>
              <div class="name">
                <strong> <%= sp.name %>  </strong> 
              </div>
              <%  sp.phones.each do |phone| %>
                <div class="phone">
                  <strong> <%= phone.number_types.capitalize %>:  </strong>
                  <a href="tel:<%= phone.number %>">
                    <%= phone.number %> 
                  </a> 
                </div>
              <% end %>
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>

    <div class="crud-actions"> 
      <%= link_to 'New Service Point', '/admin/service_points/new', class: 'new-button' %>
      <%= link_to 'Show', admin_department_path(dept), { class: 'show-button' } %>
      <%= link_to 'Edit', edit_admin_department_path(dept), { class: 'edit-button' } %>
      <%= link_to 'Destroy', admin_department_path(dept), method: :delete, class: 'delete-button', data: { confirm: 'Are you sure?' }, title:'delete' %>
    </div>
  </div>
<% end %>

<div class="bottom-action"> 
  <%= link_to 'New Department', new_admin_department_path, { class: 'new-button' } %>
</div>

app/views/admin/departments/new.html.erb
<h2> Create New Department</h2>

<%= render 'form', department: @department %>

app/views/admin/departments/show.html.erb
<h2> <%= @department.name %> </h2>

<div class="description">
  <strong> Description: </strong> 
  <%= @department.description %>
</div>

<% if @department.service_points.present? && !@department.service_points.nil? %>
  <% @department.service_points.each do |sp| %>
  <div class="service-points">
    <strong> Service Point(s): </strong>
      <ul>
        <li> 
          <strong> Name : </strong> <%= sp.name %>
           <% sp.phones.each do |phone| %>
          <ul class="phone-item">
              <li>
                <%= phone.number %>
                <span class="micro"> (<%= phone.number_types.capitalize %>) </span>
              </li>
            </ul>
          <% end %>
        </li>
      </ul>
  </div>
  <% end %>
<% end %>

<div class="show-action">
    <div class="actions"> 
      <%= link_to '<span class="fas fa-building"></span> Departments'.html_safe, '/admin/departments', { class: 'new-button' } %>
      <%= link_to '<span class="fas fa-edit"></span> Edit'.html_safe, edit_admin_department_path(@department), { class: 'edit-button' } %>
      <%= link_to '<span class="fas fa-trash"></span> Destroy'.html_safe, admin_department_path(@department), method: :delete, class: 'delete-button', data: { confirm: 'Are you sure?' }, title:'delete' %>
    </div>
  </div>