config/routes.rb
Rails.application.routes.draw do
  # home index
  root to: 'application#home'

  get '/home',
      to: 'application#home',
      as: 'home'

  # auth
  get '/login',
      to: 'application#login',
      as: 'login'

  get '/signout', 
      to: 'application#signout', 
      as: 'signout'

  get '/logout',
      to: 'application#logout',
      as: 'logout'

  # buildings
  get '/buildings',
      to: 'buildings#list',
      as: 'building_list'

  get '/buildings/:id/employees',
      to: 'buildings#employees',
      as: 'building_employees'

  get '/buildings/:id',
      to: 'buildings#details',
      as: 'building_details'

  # employees
  get 'employees',
      to: 'employees#list',
      as: 'employee_list'

  get '/employee/:id',
      to: 'employees#profile',
      as: 'employee_profile'

  # departments
  get 'departments',
      to: 'department#list',
      as: 'department_list'

  get 'departments/:id',
      to: 'department#details',
      as: 'department_details'

  get 'departments/:id/employees',
      to: 'department#employees',
      as: 'department_employees'

  # liaisons
  get '/liaisons',
      to: 'liaison#list',
      as: 'liaisons_list'
  get '/subjects', to: redirect('/liaisons', status: 302)

  # search
  get '/search',
      to: 'search#index',
      as: 'search_index'

  # admin
  get '/admin',
      to: 'admin#home',
      as: 'admin_home'

  # phone lists
  get '/phonelist/morgantown', to: 'phone_list#morgantown'
  get '/phonelist/all', to: 'phone_list#all'

  # API
  namespace :api do
    namespace :v1, defaults: { format: :json } do
        # buildings
        get '/buildings/:id/employees', to: 'buildings#employees'
        get '/buildings/:id', to: 'buildings#details'
        get '/buildings', to: 'buildings#list'

        # departments
        get '/departments', to: 'departments#list'
        get '/departments/:id', to: 'departments#details'
        get '/departments/:id/employees', to: 'departments#employees'
        
        # employees
        get 'employees', to: 'employees#list'
        get 'employees/:id', to: 'employees#profile'
    end
  end

  # admin namespaces for crud tasks
  namespace :admin do
    resources :buildings,
              :departments,
              :employees,
              :floors,
              :subjects,
              :service_points

    resources :employees do
      resources :leadership, only: [:index, :edit, :update, :destroy]
    end
  end
end

app/models/employee.rb
# Employee
#
# @description: A sub class of the user model uses single table inheritance to
# determine type of profile and add extra details to user model
# @author David J. Davis, Tracy A. McCormick
# @data_model
# @since 0.0.1
class Employee < User
  # validations
  validates :job_title,
            length: { maximum: 70 },
            allow_blank: true

  validates :university_classification,
            presence: true,
            length: { within: 2..70 }

  validates :description, length: { maximum: 1500 }

  # associations
  has_many :departmentable, dependent: :nullify
  has_many :departments, through: :departmentable
  has_many :addresses, as: :addressable, dependent: :destroy
  has_many :phones, as: :phoneable, dependent: :destroy
  has_many :websites, as: :webable, dependent: :destroy  
  has_many :subjectables, dependent: :nullify
  has_many :subjects, through: :subjectables

  # form logic
  accepts_nested_attributes_for :addresses, allow_destroy: true
  accepts_nested_attributes_for :phones, allow_destroy: true
  accepts_nested_attributes_for :websites, allow_destroy: true

  # concerns
  include Imageable
  include Searchable

  # scopes
  scope :visible, -> { where(status: 'enabled') }
  scope :order_name, -> { order(:last_name, :first_name) }

  # Resume / CV Option
  mount_uploader :resume, ResumeUploader

  # resume?
  # -----------------------------------------------------
  # @author David J. Davis
  # @description looks to see if the user has a resume or cv attached
  # will return true if there is a file, false if no file
  # @return boolean
  def resume?
    !resume.file.nil?
  end

  # Elastic Search Settings
  # -----------------------------------------------------

  # Elastic Search Index settings.
  # These are set in the model to index only specific information.
  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :display_name
      indexes :first_name
      indexes :last_name
      indexes :preferred_name
      indexes :job_title
      indexes :university_classification
      indexes :description
      indexes :status
      indexes :subjects do
        indexes :name 
      end      
      indexes :departments do
        indexes :name
      end      
      indexes :phones do
        indexes :number 
      end
      indexes :websites do
        indexes :name_of_url
        indexes :url 
      end      
    end
  end

  # @author David J. Davis
  # @description indexed json, this will help with search rankings.
  # rake environment elasticsearch:import:model CLASS='Employee' SCOPE="visible" FORCE=y
  def as_indexed_json(_options)
    # puts type    
    as_json(
      methods: [:display_name],
      only: %i[id status first_name last_name preferred_name display_name description job_title university_classification image],
      include: {
        departments: { methods: [:name, :building_name],
                       only: %i[name building_name] },
        subjects: { methods: [:name], only: [:name] },
        phones: { only: :number },
        websites: { only: :url }
      }
    )
  end
end

app/controllers/admin/employees_controller.rb
# Employees Controller
# @author David J. Davis
# Sets data for views, sets redirects, sets errors
class Admin::EmployeesController < AdminController
  # before_actions
  before_action :set_employee, only: %i[show edit update destroy]

  # GET admin/Employees
  # GET admin/Employees.json
  def index
    @employees = Employee.all.order(:last_name, :first_name)
  end

  # GET /Employees/1
  # GET /Employees/1.json
  def show; end

  # GET /Employees/new
  def new
    @employee = Employee.new
  end

  # GET /Employees/1/edit
  def edit; end

  # POST /Employees
  # POST /Employees.json
  def create
    @employee = Employee.new(employee_params)
    respond_to do |format|
      if @employee.save
        format.html { redirect_to admin_employee_path(@employee), success: I18n.t('employee.success') }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /Employees/1
  # PATCH/PUT /Employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to admin_employee_path(@employee), success: I18n.t('employee.edited') }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /Employees/1
  # DELETE /Employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to '/admin/employees', success: I18n.t('employee.deleted') }
    end
  end

  # Private Methods
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def employee_params
    params.require(:employee).permit(
      :prefix,
      :suffix,
      :first_name,
      :middle_name,
      :last_name,
      :preferred_name,
      :image,
      :image_cache,
      :remove_image, 
      :resume,
      :resume_cache,
      :remove_resume, 
      :wvu_username,
      :email,
      :job_title,
      :university_classification,
      :description,
      :status,
      :role,
      addresses_attributes: %i[id line1 line2 city state zip _destroy],
      phones_attributes: %i[id number_types number _destroy],
      websites_attributes: %i[id name_of_url url _destroy],
      subject_ids: [], 
      department_ids: []
    )
  end
end

app/controllers/api/v1/employees_controller.rb
class Api::V1::EmployeesController < ApplicationController
  # concerns
  include PublishApi
  before_action :public_headers

  # serializers
  include Version1::BuildingsSerializer
  include Version1::EmployeesSerializer

  def list
    employees = Employee.includes(:phones, :websites, :departments, :departmentable, :addresses)
                        .where(status: 'enabled')
                        .order(:last_name, :first_name)
    render json: serialize_employees(employees)
  end

  def profile
    employee = Employee.includes(:phones, :websites, :departments, :departmentable, :addresses, :subjects)
                       .where(id: params[:id], status: 'enabled')
                       .order(:last_name, :first_name)
                       .first
    render json: serialize_employee(employee)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def list
    @employees = Employee.includes(:phones, :departments, :departmentable, :addresses, :websites)
                         .where(status: 'enabled')
                         .order(:last_name, :first_name)
  end

  def profile
    @employee = Employee.includes(:phones, :departments, :departmentable, :addresses, :subjects, :websites)
                        .where(id: params[:id], status: 'enabled')
                        .order(:last_name, :first_name)
                        .first
  end
end

app/views/admin/employees/_form.html.erb
<%= form_for [:admin, employee], html: { multipart: true } do |f| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h3>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset> 
    <legend> Profile Information </legend>
    <div class="row"> 
      <div class="field one-fourth">
        <%= f.label :prefix, class:'select-label' %>
        <div class="select-style">
          <%= f.select :prefix, options_for_select(name_prefixes, selected: employee.prefix ), include_blank: "Select a Prefix" %>
        </div>
      </div>

      <div class="field three-fourth last">
        <%= f.label :first_name, class: 'required' %>
        <%= f.text_field :first_name, placeholder: "Joanna" %>
      </div>

      <div class="field two-fourth">
        <%= f.label :preferred_name, class: 'required' %>
        <%= f.text_field :preferred_name, placeholder: "Smith" %>
      </div>
      
      <div class="field two-fourth last">
        <%= f.label :middle_name %>
        <%= f.text_field :middle_name, placeholder: "Q. (Quinn)" %>
      </div>

      <div class="field three-fourth">
        <%= f.label :last_name, class: 'required' %>
        <%= f.text_field :last_name, placeholder: "Smith" %>
      </div>

      <div class="field one-fourth last">
        <%= f.label :suffix, class:'select-label' %>
        <div class="select-style">
          <%= f.select :suffix, options_for_select(name_suffixes, selected: employee.suffix ), include_blank: "Select a Suffix" %>
        </div>
      </div>
    </div>
  </fieldset>

  <fieldset> 
    <legend> File Uploads </legend>
    <div class="field full">
      <%= image_tag employee.image_url, { class:'preview-image' } if employee.image? %>
      <%= f.label :image, 'Profile Image' %>
      <%= f.file_field :image %>
      <% if employee.image? %>
        <div class="checkbox-wrapper">
          <div class="checkbox">
            <%= f.check_box :remove_image %>
            <%= f.label :remove_image, 'Remove Image' %>
          </div>
        </div>
      <% end %>
      <%= f.hidden_field :image_cache %>
    </div>

    <div class="field full">
      <%= link_to 'View Current CV / Resume', employee.resume.url, target: :_blank if employee.resume? %>
      <%= f.label :resume, 'CV / Resume Upload' %>
      <%= f.file_field :resume %>
      <% if employee.resume? %>
        <div class="checkbox-wrapper">
          <div class="checkbox">
            <%= f.check_box :remove_resume %>
            <%= f.label :remove_resume, 'Remove Resume' %>
          </div>
        </div>
      <% end %>
      <%= f.hidden_field :resume_cache %>
    </div>

  </fieldset>

  <fieldset>
    <legend> WVU Profile Information </legend>
     <div class="row"> 
      <div class="field half">
        <%= f.label :wvu_username, class: 'required' %>
        <%= f.text_field :wvu_username, placeholder: "jqsmith001" %>
      </div>

      <div class="field half last">
        <%= f.label :email, class: 'required' %>
        <%= f.text_field :email, placeholder: "jqsmith@mail.wvu.edu" %>
      </div>
    </div>

    <div class="row"> 
      <div class="field half">
        <%= f.label :job_title, class: 'required' %>
        <%= f.text_field :job_title, placeholder: "Accountant EBO" %>
      </div>

      <div class="field half last">
        <%= f.label :university_classification, class: 'required' %>
        <%= f.text_field :university_classification, placeholder: "Business Professional" %>
      </div>

      <div class="field full">
        <%= f.label :department_ids, 'Departments' %>
        <%# f.collection_select :department_ids, Department.all.order(:name), :id, :name, { include_hidden: false }, { multiple: true }%>
    
        <%= f.grouped_collection_select :department_ids, Building.all, :departments, :name, :id, :name, { include_hidden: false }, { multiple: true } %>
        

        <div class="half select">
          <a href='#' id='department_select_all'> Select All </a>
        </div>
        
        <div class="half deselect">
          <a href='#' id='department_deselect_all'> Deselect All </a>
        </div>
      </div>

      <div class="field full">
        <%= f.label :description %>
        <%= f.text_area :description, placeholder: "Basic description of what the employee does in simple terms for the public." %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend> Application Access Information </legend>
    <div class="row">
      <div class="field half">
        <%= f.label :role, 'User Role', class:'required' %>
        <div class="select-style">
            <%= f.select :role, options_for_select(User.roles.keys.to_a, selected: f.object.role) %>
        </div>
      </div>

      <div class="field half last">
       <%= f.label :status, 'User Status', class:'required' %>
        <div class="select-style">
            <%= f.select :status, options_for_select(User.statuses.keys.to_a, selected: f.object.status || 'enabled') %>
        </div>
      </div>

      <div class="micro-text"> 
        <%= t('notes.user_status') %>
      </div>
    </div>
  </fieldset>

  <!-- Addresses -->
  <%= f.fields_for :addresses do |form| %>
    <%= render "address", form: form %>
  <% end %>
  <%= link_to_add_fields "Add Address", f, :addresses %>

  <!-- Phones -->
  <%= f.fields_for :phones do |form| %>
    <%= render "phone", form: form %>
  <% end %>
  <%= link_to_add_fields "Add Phones", f, :phones %>

  <!-- Websites -->
  <%= f.fields_for :websites do |form| %>
    <%= render "website", form: form %>
  <% end %>
  <%= link_to_add_fields "Add Websites", f, :websites %>  

  <!-- Subjects -->
   <fieldset>
    <legend> Subject Liasons </legend>
    <div class="field full">
      <%= f.label :subject_ids, 'Subjects' %>
      <%= f.collection_select :subject_ids, Subject.all.order(:name), :id, :name, { include_hidden: false }, { multiple: true }%>

      <div class="half select">
        <a href='#' id='employee_select_all'> Select All </a>
      </div>
      
      <div class="half deselect">
        <a href='#' id='employee_deselect_all'> Deselect All </a>
      </div>
    </div>
  </fieldset>

  <div class="actions">
    <%= link_to 'Cancel', admin_employees_path, class: 'cancel-button' %>
    <%= f.submit 'Submit', class: 'submit-button' %>
  </div>
<% end %>

app/views/admin/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

app/views/admin/employees/index.html.erb
<div class="top-action">
  <h2> Manage Employees </h2>
  <%= link_to 'New Employee', new_admin_employee_path, { class: 'new-button' } %>
</div>

<div class="search-filter">
  <label for="employee_filter"> Filter Employees </label>
  <input id="employee_filter" type="text" class="reset search-dom" placeholder="Employee Filters"/>

  <div class="micro-text"> 
    Note: Filter is meant to trim down the list of employees pretty quickly and only uses the first word as a match to a variety of keywords. <span class="warning"> It is not advised to use more than 1 word. </span>
  </div>
</div>

<% @employees.each do |employee| %>
  <div class="crud-list employee-list">
    
    <div class="hidden keywords">
      <%= employee.first_name %>
      <%= employee.last_name %>
      <%= employee.middle_name %>
      <%= employee.preferred_name %>
      <%= employee.status %>
      <%= employee.role %>
    </div>

    <div class="image">
      <img src="<%= employee.image %>" alt="employees profile image"/>
    </div>

    <div class="text-attributes">
      <ul>
        <li> 
          <strong> Name: </strong> 
          <%= employee.display_name %>
        </li>

        <li>
          <strong> Email: </strong>
          <%= employee.email %>
        </li>

        <li>
          <strong> Role: </strong>
          <%= employee.role&.capitalize %>
        </li>

        <li>
          <strong> Status: </strong>
          <%= employee.status&.capitalize %>
        </li>

      </ul>
    </div>

    <div class="crud-actions">
      <%= link_to raw('<span class="fas fa-user-alt"></span>View'), admin_employee_path(employee), { class: 'show-button' } %>
      <%= link_to raw('<span class="fa fa-user-edit"></span> Edit'), edit_admin_employee_path(employee), { class: 'edit-button' } %>
      <%= link_to raw('<span class="fas fa-user-tag"></span> Roles'), admin_employee_leadership_index_path(employee), { class: 'new-button' } %>
      <%= link_to raw('<span class="fas fa-user-times"></span> Delete'), admin_employee_path(employee), method: :delete, class: 'delete-button', data: { confirm: 'Are you sure?' }, title:'delete' %>
    </div>
  </div>
<% end %>

<div class="bottom-action"> 
  <%= link_to 'New Employee', new_admin_employee_path, { class: 'new-button' } %>
</div>

app/views/admin/employees/new.html.erb
<h2> New Employee </h2>

<%= render 'form', employee: @employee %>

app/views/admin/employees/show.html.erb
<h2 class="hidden"> Showing <%= @employee.display_name %> </h2>

<div class="employee-card">

  <div class="profile-banner">
    <img src="<%= @employee.image %>" alt="Picture of <%= @employee.display_name %>"/>
  </div>

  <div class="profile-text">
    <div class="name-title wvu-h4" id="profile_name"> 
        <%= @employee.display_name %> 
    </div>

    <div class="job-title">
      <% unless @employee.job_title.nil? || @employee.job_title.empty? %>
        <div class="micro"> <%= @employee.job_title %> </div>
      <% end %>
      <% unless @employee.university_classification.nil? || @employee.university_classification.empty? %>
          <div class="micro">  <%= @employee.university_classification %>  </div> 
      <% end %>
    </div>

    <h4> Employee Details </h4>
    <div class="details">
      <% if @employee.prefix.present? %>
      <div>
        <strong> Prefix: </strong>
        <%= @employee.prefix %>
      </div>
      <% end %>

      <div>
        <strong> First Name: </strong>
        <%= @employee.first_name %>
      </div>

      <div>
        <strong> Middle Name: </strong>
        <%= @employee.middle_name %>
      </div>

      <div>
        <strong> Last Name: </strong>
        <%= @employee.last_name %>
      </div>

      <div>
        <strong> Preferred Name: </strong>
        <%= @employee.preferred_name %>
      </div>

      <% if @employee.suffix.present? %>
      <div>
        <strong> Suffix: </strong>
        <%= @employee.suffix %>
      </div>
      <% end %>

      <div>
        <strong> Email: </strong>
        <%= @employee.email %>
      </div>

      <div>
        <strong> WVU Username: </strong>
        <%= @employee.wvu_username %>
      </div>

      <div>
        <strong> Unviersity Classification: </strong>
        <%= @employee.university_classification %>
      </div>

      <div>
        <strong> Job Title: </strong>
        <%= @employee.job_title %>
      </div>

      <div>
        <strong> Job Description: </strong>
        <%= @employee.description %>
      </div>
      
      <div>
        <strong> Role: </strong>
        <%= @employee.role.capitalize %>
      </div>
      
      <div>
        <strong> Status: </strong>
        <%= @employee.status.capitalize %>
      </div>
    </div>

    <h4> Department(s) </h4>
    <div class="departments">
      <% @employee.departments.each do |dept| %>
        <%= dept.name %> - <%= dept.building.name %>
      <% end %>
    </div>

    <h4> Contact </h4>
    <div class="contact">
      <% if @employee.addresses.present? %>
      <div class="addresses">  
        <% @employee.addresses.each do |address| %>
          <div class="address-item">
            <span class="fas fa-address-card"></span>
            <%= address.human_readable %>
          </div>
        <% end %>
      </div>
      <% end %>

      <% if @employee.phones.present? %>
      <div class="phones">  
        <% @employee.phones.each do |phone| %>
          <div class="phone-item">
            <span class="<%= phone_icon_class(phone) %>"></span>
            <a class="wvu-profiles-index__phone" href="tel:<%= phone.number %>"><%= phone.number %></a>
            <span class="micro"> (<%= phone.number_types.capitalize %>) </span>
          </div>
        <% end %>
      </div>
      <% end %>

      <% if @employee.websites.present? %>
      <div class="websites">  
        <% @employee.websites.each do |website| %>
          <div class="website-item">
            <span class="fas fa-link"></span>
            <a href="<%= website.url %>">
              <%= website.name_of_url %></a>
          </div>
        <% end %>
      </div>
      <% end %>      

      <div class="email">
        <span class="fas fa-envelope"></span>
        <a href="mailto:<%= @employee.email %>">
          <%= @employee.email %>
        </a>
      </div>
    </div>

    <% if @employee.subjects.present? %>
    <h4> Subjects </h4>
    <ul class="subject-tags"> 
      <% @employee.subjects.sort.each do |subject| %>
        <li> <%= subject.name %> </li>
      <% end %>
    </ul>
    <% end %>

    <div class="micro-text">
      Created at <%= @employee.created_at.strftime("%B %d, %Y at %I:%M%p") %> <br/> 
      Updated at <%= @employee.updated_at.strftime("%B %d, %Y at %I:%M%p")%>
    </div>

    <div class="actions"> 
      <%= link_to '<span class="fas fa-user"></span> Employees'.html_safe, '/admin/employees', { class: 'new-button' } %>
      <%= link_to '<span class="fas fa-edit"></span> Edit'.html_safe, edit_admin_employee_path(@employee), { class: 'edit-button' } %>
      <%= link_to '<span class="fas fa-trash"></span> Destroy'.html_safe, admin_employee_path(@employee), method: :delete, class: 'delete-button', data: { confirm: 'Are you sure?' }, title:'delete' %>
    </div>
  </div>
</div>